<a href="https://colab.research.google.com/github/samslotin1/Hackathon_1/blob/main/Hackathon_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("movie_users_1000.csv")
df.describe()

               age       rating
count  5536.000000  5536.000000
mean     41.887283     2.972363
std      13.672579     1.414518
min      18.000000     1.000000
25%      30.000000     2.000000
50%      42.000000     3.000000
75%      53.250000     4.000000
max      65.000000     5.000000

In [3]:
list(df.columns)

['name', 'age', 'preferences', 'movie', 'genre', 'director', 'rating']

In [4]:
print(df["genre"])

0       animation
1         romance
2          comedy
3           crime
4           crime
          ...
5531    animation
5532        crime
5533       sci-fi
5534       sci-fi
5535    animation
Name: genre, Length: 5536, dtype: object

In [5]:
df['genre'].unique()
freq = df['genre'].value_counts()
print(freq)

genre
action       1139
animation     849
sci-fi        814
drama         567
romance       539
crime         528
horror        509
thriller      300
comedy        291
Name: count, dtype: int64

In [6]:
grouped = df.groupby(['age','movie']).value_counts()
print(grouped)

age  movie         name      preferences         genre      director         rating
18   Alien         Karen     drama, thriller     horror     Ridley Scott     1         1
     Finding Nemo  Amber     action, thriller    animation  Andrew Stanton   3         1
                   Gregory   animation, romance  animation  Andrew Stanton   4         1
     Forrest Gump  James     action, fantasy     drama      Robert Zemeckis  5         1
                   Jonathan  fantasy, crime      drama      Robert Zemeckis  1         1
                                                                                      ..
65   Titanic       Omar      crime, action       romance    James Cameron    5         1
     Toy Story     Brittany  horror, sci-fi      animation  John Lasseter    5         1
                   Candice   action, comedy      animation  John Lasseter    5         1
                   Omar      comedy, sci-fi      animation  John Lasseter    3         1
                             crime, action       animation  John Lasseter    3         1
Name: count, Length: 5397, dtype: int64

In [7]:
print(df.head())

        name  age        preferences     movie      genre        director  \
0  Stephanie   24  animation, sci-fi     Shrek  animation  Andrew Adamson
1  Stephanie   24  animation, sci-fi   Titanic    romance   James Cameron
2  Stephanie   24  animation, sci-fi  Superbad     comedy    Greg Mottola
3  Stephanie   24  animation, sci-fi     Joker      crime   Todd Phillips
4  Stephanie   24  animation, sci-fi     Joker      crime   Todd Phillips

   rating
0       2
1       5
2       5
3       5
4       5

In [8]:
stephanie = df[df["name"] == "Stephanie"]

favorites = stephanie[stephanie["rating"] >= 4]

print(favorites[["movie", "genre", "director", "rating"]])

                movie      genre           director  rating
1             Titanic    romance      James Cameron       5
2            Superbad     comedy       Greg Mottola       5
3               Joker      crime      Todd Phillips       5
4               Joker      crime      Todd Phillips       5
6           Inception     sci-fi  Christopher Nolan       4
7        Interstellar     sci-fi  Christopher Nolan       4
3040  The Dark Knight     action  Christopher Nolan       5
3041          Get Out     horror       Jordan Peele       5
3043        John Wick     action     Chad Stahelski       4
3045            Joker      crime      Todd Phillips       4
3277            Joker      crime      Todd Phillips       5
3278            Joker      crime      Todd Phillips       5
3279            Joker      crime      Todd Phillips       4
3280         Superbad     comedy       Greg Mottola       4
3742            Shrek  animation     Andrew Adamson       4
3743     Finding Nemo  animation     Andrew Stanton       4
3744            Alien     horror       Ridley Scott       4
3745        Gladiator     action       Ridley Scott       5
3747     Interstellar     sci-fi  Christopher Nolan       5
4094        Gladiator     action       Ridley Scott       5

In [9]:
stephanie.groupby("genre")["rating"].mean()

genre
action       4.750000
animation    2.571429
comedy       3.750000
crime        4.142857
drama        1.000000
horror       4.000000
romance      2.333333
sci-fi       3.500000
thriller     3.000000
Name: rating, dtype: float64

In [10]:
favorite_genres = ["action", "crime", "horror"]
df['genre'].isin(favorite_genres)

0       False
1       False
2       False
3        True
4        True
        ...
5531    False
5532     True
5533    False
5534    False
5535    False
Name: genre, Length: 5536, dtype: bool

In [11]:
filtered_movies = df[df['genre'].isin(favorite_genres)]
print(filtered_movies.head())

         name  age        preferences               movie   genre  \
3   Stephanie   24  animation, sci-fi               Joker   crime
4   Stephanie   24  animation, sci-fi               Joker   crime
12      Holly   21  horror, animation  Mad Max: Fury Road  action
14      Holly   21  horror, animation  Mad Max: Fury Road  action
15    Kristen   35    sci-fi, fantasy               Joker   crime

         director  rating
3   Todd Phillips       5
4   Todd Phillips       5
12  George Miller       5
14  George Miller       1
15  Todd Phillips       3

In [12]:
stephanie_watched = stephanie["movie"].unique()

print(stephanie_watched)

['Shrek' 'Titanic' 'Superbad' 'Joker' 'The Notebook' 'Inception'
 'Interstellar' 'The Dark Knight' 'Get Out' 'Forrest Gump' 'John Wick'
 'The Matrix' 'Finding Nemo' 'Alien' 'Gladiator' 'Se7en' 'Toy Story'
 'Pulp Fiction']

In [13]:
all_movies = df["movie"].unique()
print(all_movies)

['Shrek' 'Titanic' 'Superbad' 'Joker' 'The Notebook' 'Inception'
 'Interstellar' 'Forrest Gump' 'The Matrix' 'Mad Max: Fury Road'
 'Gladiator' 'Toy Story' 'Finding Nemo' 'Alien' 'Get Out'
 'The Dark Knight' 'Pulp Fiction' 'Se7en' 'John Wick' 'Parasite']

In [14]:
df[df["movie"] == "Parasite"]

         name  age          preferences     movie  genre      director  rating
102    Andrea   53      romance, comedy  Parasite  drama  Bong Joon-ho       3
123      Tony   58    romance, thriller  Parasite  drama  Bong Joon-ho       3
127     James   46         crime, drama  Parasite  drama  Bong Joon-ho       1
180   Jessica   40       drama, fantasy  Parasite  drama  Bong Joon-ho       1
183   Tristan   41      action, romance  Parasite  drama  Bong Joon-ho       2
...       ...  ...                  ...       ...    ...           ...     ...
5461    Bobby   31         drama, crime  Parasite  drama  Bong Joon-ho       2
5479   Dustin   41  animation, thriller  Parasite  drama  Bong Joon-ho       3
5512  Douglas   46       drama, romance  Parasite  drama  Bong Joon-ho       5
5513  Douglas   46       drama, romance  Parasite  drama  Bong Joon-ho       5
5523   Rhonda   50  thriller, animation  Parasite  drama  Bong Joon-ho       2

[282 rows x 7 columns]

In [15]:
~df['movie'].isin(stephanie_watched)

0       False
1       False
2       False
3       False
4       False
        ...
5531    False
5532    False
5533    False
5534    False
5535    False
Name: movie, Length: 5536, dtype: bool

In [16]:
len(stephanie_watched)

18

In [17]:
len(df["movie"].unique())

20

In [18]:
def recommend_for_user(user_name):
    user_data = df[df["name"] == user_name]

    genre_ratings = user_data.groupby("genre")["rating"].mean()

    user_watched = user_data["movie"].unique()

    all_movies = df["movie"].unique()

    unseen_movies = np.setdiff1d(all_movies, user_watched)

    print("Genre ratings:")
    print(genre_ratings)

    print("Unseen movies:")
    print(unseen_movies)


recommend_for_user("Stephanie")

Genre ratings:
genre
action       4.750000
animation    2.571429
comedy       3.750000
crime        4.142857
drama        1.000000
horror       4.000000
romance      2.333333
sci-fi       3.500000
thriller     3.000000
Name: rating, dtype: float64
Unseen movies:
['Mad Max: Fury Road' 'Parasite']

In [19]:
recommend_for_user("Stephanie")

Genre ratings:
genre
action       4.750000
animation    2.571429
comedy       3.750000
crime        4.142857
drama        1.000000
horror       4.000000
romance      2.333333
sci-fi       3.500000
thriller     3.000000
Name: rating, dtype: float64
Unseen movies:
['Mad Max: Fury Road' 'Parasite']

In [20]:
 df[df['movie'] == 'Parasite']

         name  age          preferences     movie  genre      director  rating
102    Andrea   53      romance, comedy  Parasite  drama  Bong Joon-ho       3
123      Tony   58    romance, thriller  Parasite  drama  Bong Joon-ho       3
127     James   46         crime, drama  Parasite  drama  Bong Joon-ho       1
180   Jessica   40       drama, fantasy  Parasite  drama  Bong Joon-ho       1
183   Tristan   41      action, romance  Parasite  drama  Bong Joon-ho       2
...       ...  ...                  ...       ...    ...           ...     ...
5461    Bobby   31         drama, crime  Parasite  drama  Bong Joon-ho       2
5479   Dustin   41  animation, thriller  Parasite  drama  Bong Joon-ho       3
5512  Douglas   46       drama, romance  Parasite  drama  Bong Joon-ho       5
5513  Douglas   46       drama, romance  Parasite  drama  Bong Joon-ho       5
5523   Rhonda   50  thriller, animation  Parasite  drama  Bong Joon-ho       2

[282 rows x 7 columns]

In [21]:
import pandas as pd

# Load dataset
df = pd.read_csv("movie_users_1000.csv")

# Get Stephanie's ratings
stephanie = df[df["name"] == "Stephanie"]

# Create master movie list (one row per movie)
all_movies = df[["movie", "genre"]].drop_duplicates()

# Recommendation function
def recommend_by_genre_taste(user_ratings_df, all_movies_df):

    # Average rating by genre
    genre_avg = (
        user_ratings_df
        .groupby("genre")["rating"]
        .mean()
        .reset_index()
        .rename(columns={"rating": "score"})
    )

    # Movies already seen
    seen = user_ratings_df["movie"].tolist()

    # Movies not seen
    unseen = all_movies_df[
        ~all_movies_df["movie"].isin(seen)
    ].copy()

    # Add genre scores and sort
    recs = (
        unseen
        .merge(genre_avg, on="genre", how="left")
        .sort_values("score", ascending=False)
        .reset_index(drop=True)
    )

    return recs


# Run recommender
recommendations = recommend_by_genre_taste(
    stephanie,
    all_movies
)

print(recommendations)

                movie   genre  score
0  Mad Max: Fury Road  action   4.75
1            Parasite   drama   1.00